// Instance port resolver Automation specs (P1.4).
//
// Ports Unity Open MCP's InstancePortResolverTests
// (packages/bridge/Tests/Editor/Bridge/InstancePortResolverTests.cs) to Unreal.
// Pins the SHA-256 hash formula + path normalization + override precedence so
// it can never silently drift from the MCP server's mirror
// (mcp-server/src/instance-discovery.ts). Cross-side consistency is the whole
// point: the bridge and the MCP server compute the same port for the same
// project path with zero shared config.
//
// If any constant here changes, update the matching test in
// mcp-server/src/instance-discovery.test.ts (P1.6) AND Unity's
// InstancePortResolverTests.cs in the same task.
#if WITH_DEV_AUTOMATION_TESTS

#include "CoreMinimal.h"
#include "Misc/AutomationTest.h"

#include "Bridge/UnrealOpenMcpInstancePortResolver.h"
#include "Crypto/UnrealOpenMcpSha256.h"

BEGIN_DEFINE_SPEC(
	FUnrealOpenMcpPortResolverSpec,
	"UnrealOpenMcp.Bridge.PortResolver",
	EAutomationTestFlags::EditorContext | EAutomationTestFlags::ProductFilter)
END_DEFINE_SPEC(FUnrealOpenMcpPortResolverSpec)

void FUnrealOpenMcpPortResolverSpec::Define()
{
	// Pinned cross-side paths. Both sides (C++ bridge + TS MCP server + Unity
	// bridge) MUST agree:
	//   /Users/foo/MyGame → port 22028, hash prefix dca5061f6f21537c
	//   /some/path        → port 29602, hash prefix eda6cf0b63f1a1d2
	// Generated by the same 8-byte-prefix SHA-256 formula on all sides.
	const FString SamplePath = TEXT("/Users/foo/MyGame");
	const FString SamplePathAlt = TEXT("/some/path");
	const int32 SamplePathExpectedPort = 22028;
	const FString SamplePathExpectedHashPrefix = TEXT("dca5061f6f21537c");
	const int32 SamplePathAltExpectedPort = 29602;

	Describe("SHA-256", [this]()
	{
		// Pin a known SHA-256 vector so the self-contained impl is anchored to
		// Node crypto.createHash('sha256'). If this breaks, the resolver's hash
		// has drifted from the TS mirror.
		It("produces the canonical empty-string digest", [this]()
		{
			// Node: crypto.createHash('sha256').update('').digest('hex')
			const FString Digest = FUnrealOpenMcpSha256::HexDigest(TEXT(""));
			TestEqual(
				TEXT("empty-string SHA-256"),
				Digest,
				FString(TEXT("e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855")));
		});

		It("produces the canonical 'abc' digest", [this]()
		{
			// Node: crypto.createHash('sha256').update('abc').digest('hex')
			const FString Digest = FUnrealOpenMcpSha256::HexDigest(TEXT("abc"));
			TestEqual(
				TEXT("'abc' SHA-256"),
				Digest,
				FString(TEXT("ba7816bf8f01cfea414140de5dae2223b00361a396177a9cb410ff61f20015ad")));
		});

		It("produces the canonical long-string digest", [this]()
		{
			// Node: crypto.createHash('sha256').update('The quick brown fox...').digest('hex')
			const FString Digest = FUnrealOpenMcpSha256::HexDigest(
				TEXT("The quick brown fox jumps over the lazy dog"));
			TestEqual(
				TEXT("long-string SHA-256"),
				Digest,
				FString(TEXT("d7a8fbb307d7809469ca9abcb0082e4f8d5651e46d3cdb762d02d0bf37c9e592")));
		});
	});

	Describe("ProjectHash", [this]()
	{
		It("is stable across calls", [this]()
		{
			const FString A = FUnrealOpenMcpInstancePortResolver::ProjectHash(SamplePath);
			const FString B = FUnrealOpenMcpInstancePortResolver::ProjectHash(SamplePath);
			TestEqual(TEXT("same path hashes the same"), A, B);
		});

		It("is lowercase hex SHA-256", [this]()
		{
			const FString Hash = FUnrealOpenMcpInstancePortResolver::ProjectHash(SamplePath);
			TestEqual(TEXT("64 chars"), Hash.Len(), 64);
			TestEqual(
				TEXT("first 8 bytes pinned cross-side"),
				Hash.Left(16),
				SamplePathExpectedHashPrefix);
			for (int32 i = 0; i < Hash.Len(); ++i)
			{
				const TCHAR C = Hash[i];
				const bool bOk = (C >= TEXT('0') && C <= TEXT('9')) || (C >= TEXT('a') && C <= TEXT('f'));
				TestTrue(FString::Printf(TEXT("char[%d]='%c' is lowercase hex"), i, C), bOk);
			}
		});

		It("hashes distinct paths distinctly", [this]()
		{
			const FString A = FUnrealOpenMcpInstancePortResolver::ProjectHash(SamplePath);
			const FString B = FUnrealOpenMcpInstancePortResolver::ProjectHash(SamplePathAlt);
			TestNotEqual(TEXT("distinct paths"), A, B);
		});

		It("normalizes backslashes and trailing slashes before hashing", [this]()
		{
			const FString Forward = FUnrealOpenMcpInstancePortResolver::ProjectHash(TEXT("/Users/foo/MyGame"));
			const FString Back = FUnrealOpenMcpInstancePortResolver::ProjectHash(TEXT("\\Users\\foo\\MyGame"));
			const FString Trailing = FUnrealOpenMcpInstancePortResolver::ProjectHash(TEXT("/Users/foo/MyGame/"));
			TestEqual(TEXT("backslashes normalize"), Forward, Back);
			TestEqual(TEXT("trailing slash trimmed"), Forward, Trailing);
		});
	});

	Describe("NormalizePath", [this]()
	{
		It("returns empty for empty input", [this]()
		{
			TestEqual(
				TEXT("empty in → empty out"),
				FUnrealOpenMcpInstancePortResolver::NormalizePath(TEXT("")),
				FString());
		});

		It("preserves a lone root slash", [this]()
		{
			TestEqual(
				TEXT("lone '/' preserved"),
				FUnrealOpenMcpInstancePortResolver::NormalizePath(TEXT("/")),
				FString(TEXT("/")));
		});

		It("trims multiple trailing slashes", [this]()
		{
			TestEqual(
				TEXT("trailing slashes trimmed"),
				FUnrealOpenMcpInstancePortResolver::NormalizePath(TEXT("/foo/bar///")),
				FString(TEXT("/foo/bar")));
		});

		It("does not lowercase (case-sensitive paths)", [this]()
		{
			const FString Mixed = FUnrealOpenMcpInstancePortResolver::NormalizePath(TEXT("/Users/Foo/MyGame"));
			TestTrue(TEXT("case preserved"), Mixed.Contains(TEXT("Foo")));
			TestTrue(TEXT("case preserved"), Mixed.Contains(TEXT("MyGame")));
		});
	});

	Describe("ComputePort", [this]()
	{
		It("stays within the documented range", [this]()
		{
			const int32 Port = FUnrealOpenMcpInstancePortResolver::ComputePort(SamplePath);
			TestGreaterOrEqual(TEXT(">= PortRangeStart"), Port, FUnrealOpenMcpInstancePortResolver::PortRangeStart);
			TestLessOrEqual(
				TEXT("<= PortRangeStart + Size - 1"),
				Port,
				FUnrealOpenMcpInstancePortResolver::PortRangeStart + FUnrealOpenMcpInstancePortResolver::PortRangeSize - 1);
		});

		It("matches the pinned cross-side value", [this]()
		{
			// If this breaks, the MCP server's mirror in instance-discovery.ts
			// (P1.6) has drifted from the bridge. Update both sides together.
			TestEqual(
				TEXT("/Users/foo/MyGame → 22028"),
				FUnrealOpenMcpInstancePortResolver::ComputePort(SamplePath),
				SamplePathExpectedPort);
			TestEqual(
				TEXT("/some/path → 29602"),
				FUnrealOpenMcpInstancePortResolver::ComputePort(SamplePathAlt),
				SamplePathAltExpectedPort);
		});

		It("maps distinct paths to distinct ports", [this]()
		{
			TestNotEqual(
				TEXT("distinct ports"),
				FUnrealOpenMcpInstancePortResolver::ComputePort(SamplePath),
				FUnrealOpenMcpInstancePortResolver::ComputePort(SamplePathAlt));
		});
	});

	Describe("ResolvePort", [this]()
	{
		It("env override wins", [this]()
		{
			const int32 Port = FUnrealOpenMcpInstancePortResolver::ResolvePort(
				SamplePath, TOptional<int32>(19120), TOptional<int32>());
			TestEqual(TEXT("env wins"), Port, 19120);
		});

		It("CLI arg wins when env is missing", [this]()
		{
			const int32 Port = FUnrealOpenMcpInstancePortResolver::ResolvePort(
				SamplePath, TOptional<int32>(), TOptional<int32>(19120));
			TestEqual(TEXT("cli wins when env missing"), Port, 19120);
		});

		It("env wins over CLI", [this]()
		{
			const int32 Port = FUnrealOpenMcpInstancePortResolver::ResolvePort(
				SamplePath, TOptional<int32>(21000), TOptional<int32>(22000));
			TestEqual(TEXT("env > cli"), Port, 21000);
		});

		It("falls back to the hash when no override is set", [this]()
		{
			const int32 Port = FUnrealOpenMcpInstancePortResolver::ResolvePort(
				SamplePath, TOptional<int32>(), TOptional<int32>());
			TestEqual(TEXT("hash fallback"), Port, SamplePathExpectedPort);
		});

		It("rejects invalid overrides and falls through", [this]()
		{
			TestEqual(
				TEXT("port 0 invalid → hash"),
				FUnrealOpenMcpInstancePortResolver::ResolvePort(SamplePath, TOptional<int32>(0), TOptional<int32>()),
				SamplePathExpectedPort);
			TestEqual(
				TEXT("port 70000 invalid → hash"),
				FUnrealOpenMcpInstancePortResolver::ResolvePort(SamplePath, TOptional<int32>(70000), TOptional<int32>()),
				SamplePathExpectedPort);
			// When env is invalid but CLI is valid, CLI wins.
			TestEqual(
				TEXT("env invalid + cli valid → cli"),
				FUnrealOpenMcpInstancePortResolver::ResolvePort(SamplePath, TOptional<int32>(0), TOptional<int32>(19120)),
				19120);
		});

		It("accepts valid overrides at boundaries", [this]()
		{
			TestEqual(
				TEXT("port 1 is minimum valid"),
				FUnrealOpenMcpInstancePortResolver::ResolvePort(SamplePath, TOptional<int32>(1), TOptional<int32>()),
				1);
			TestEqual(
				TEXT("port 65535 is maximum valid"),
				FUnrealOpenMcpInstancePortResolver::ResolvePort(SamplePath, TOptional<int32>(65535), TOptional<int32>()),
				65535);
		});
	});

	Describe("LockPath", [this]()
	{
		It("ends with <projectHash>.json", [this]()
		{
			const FString Path = FUnrealOpenMcpInstancePortResolver::GetLockPath(SamplePath);
			const FString ExpectedSuffix =
				FUnrealOpenMcpInstancePortResolver::ProjectHash(SamplePath) + TEXT(".json");
			TestTrue(
				FString::Printf(TEXT("ends with %s"), *ExpectedSuffix),
				Path.EndsWith(ExpectedSuffix));
		});

		It("lives under .unreal-open-mcp/instances/", [this]()
		{
			const FString Path = FUnrealOpenMcpInstancePortResolver::GetLockPath(SamplePath);
			const FString Normalized = Path.Replace(TEXT("\\"), TEXT("/"));
			TestTrue(
				TEXT("under .unreal-open-mcp/instances/"),
				Normalized.Contains(TEXT(".unreal-open-mcp/instances/")));
		});

		It("is stable for the same project", [this]()
		{
			const FString A = FUnrealOpenMcpInstancePortResolver::GetLockPath(SamplePath);
			const FString B = FUnrealOpenMcpInstancePortResolver::GetLockPath(SamplePath);
			TestEqual(TEXT("stable"), A, B);
		});

		It("honors the instances-dir override (test sandbox)", [this]()
		{
			const FString Override = TEXT("/tmp/unreal-open-mcp-test-instances");
			const FString Path = FUnrealOpenMcpInstancePortResolver::GetLockPath(SamplePath, Override);
			TestTrue(
				TEXT("lock under override dir"),
				Path.StartsWith(TEXT("/tmp/unreal-open-mcp-test-instances/")));
		});

		It("returns empty for empty project path", [this]()
		{
			TestEqual(
				TEXT("empty project → empty path"),
				FUnrealOpenMcpInstancePortResolver::GetLockPath(TEXT("")),
				FString());
		});
	});
}

#endif // WITH_DEV_AUTOMATION_TESTS
